### ISSUE TITLE
Copyright stuff for Google Hangout Collaboration Scoring code and files

### ISSUE THREAD

**Issue by dazzaji** [ConnectionScience/collaboration-scoring#11]
Let's use MIT license for all code and for pages that are human displayed, lets use:

"Copyright, MIT.  Shared under [Creative Commons Attribution License](https://creativecommons.org/licenses/by/3.0/us/)"

**Comment by jwalsh** [comment]
Done and live.

**Comment by dazzaji** [comment]
Thanks!  Looking good at: http://p.wal.sh/communication-model/
